<?php

namespace App\Services\Printdeal;

use Illuminate\Support\Facades\Process;
use RuntimeException;

/**
 * Converts a regular (RGB) PDF into a print-ready PDF/X-1a:2001 file.
 *
 * PDF/X-1a:2001 is the exchange standard a puzzle press expects: every colour
 * separated to CMYK, no RGB or ICC-tagged colour left in the page content, and
 * a single CMYK output intent profile embedded so the printer knows the target
 * printing condition. Ghostscript does the heavy lifting; this class only
 * builds the PDF/X definition (which declares the standard and embeds the
 * output intent profile) and drives the binary.
 */
class PdfXConverter
{
    private const TIMEOUT = 60;

    public function toPdfX1a(string $pdf): string
    {
        $binary = (string) config('print.pdfx.ghostscript_binary');
        $iccProfile = (string) config('print.pdfx.icc_profile');
        $outputCondition = (string) config('print.pdfx.output_condition');

        if (! is_file($iccProfile)) {
            throw new RuntimeException("PDF/X output intent profile not found: {$iccProfile}");
        }

        $input = tempnam(sys_get_temp_dir(), 'pdfx-in-').'.pdf';
        $definition = tempnam(sys_get_temp_dir(), 'pdfx-def-').'.ps';
        $output = tempnam(sys_get_temp_dir(), 'pdfx-out-').'.pdf';

        file_put_contents($input, $pdf);
        file_put_contents($definition, $this->definition($iccProfile, $outputCondition));

        try {
            $result = Process::timeout(self::TIMEOUT)->run([
                $binary,
                // Produce a PDF/X document; this also forces the PDF 1.3
                // compatibility level the PDF/X-1a:2001 standard requires.
                '-dPDFX',
                // SAFER is kept on; the output intent profile is the only file
                // read from outside the command line, so it is allow-listed.
                '-dSAFER',
                '--permit-file-read='.$iccProfile,
                '-dBATCH',
                '-dNOPAUSE',
                '-sDEVICE=pdfwrite',
                // PDF/X-1a is a PDF 1.3 standard.
                '-dCompatibilityLevel=1.3',
                // Keep the page geometry exactly as generated; the artwork is
                // already laid out at the trim size and must not be reoriented.
                '-dAutoRotatePages=/None',
                // Separate every colour to DeviceCMYK; this also converts the
                // embedded RGB photos to CMYK. A /prepress preset is
                // deliberately NOT used: it overrides this strategy with
                // /LeaveColorUnchanged and the compatibility level with 1.7,
                // which PDF/X rejects with a "rangecheck in .putdeviceprops"
                // error on some Ghostscript builds (e.g. 10.02.1).
                '-sColorConversionStrategy=CMYK',
                '-sOutputFile='.$output,
                $definition,
                $input,
            ]);

            if ($result->failed() || ! is_file($output) || filesize($output) === 0) {
                throw new RuntimeException(
                    'Ghostscript PDF/X-1a conversion failed: '.trim($result->errorOutput() ?: $result->output()),
                );
            }

            return (string) file_get_contents($output);
        } finally {
            @unlink($input);
            @unlink($definition);
            @unlink($output);
        }
    }

    /**
     * The PDF/X definition Ghostscript prepends to the document: it tags the
     * file as PDF/X-1a:2001 and embeds the CMYK output intent profile (4
     * components, since we always convert to CMYK).
     */
    private function definition(string $iccProfile, string $outputCondition): string
    {
        $icc = $this->postScriptString($iccProfile);
        $condition = $this->postScriptString($outputCondition);

        return <<<POSTSCRIPT
        %!
        % PDF/X-1a:2001 definition generated by PdfXConverter.
        [ /GTS_PDFXVersion (PDF/X-1:2001)
          /GTS_PDFXConformance (PDF/X-1a:2001)
          /Title (artwork)
          /Trapped /False
        /DOCINFO pdfmark

        /ICCProfile {$icc} def

        [ /_objdef {icc_PDFX} /type /stream /OBJ pdfmark
        [ {icc_PDFX} << /N 4 >> /PUT pdfmark
        [ {icc_PDFX} ICCProfile (r) file /PUT pdfmark

        [ /_objdef {OutputIntent_PDFX} /type /dict /OBJ pdfmark
        [ {OutputIntent_PDFX} <<
          /Type /OutputIntent
          /S /GTS_PDFX
          /OutputCondition {$condition}
          /OutputConditionIdentifier {$condition}
          /Info {$condition}
          /RegistryName (http://www.color.org)
          /DestOutputProfile {icc_PDFX}
        >> /PUT pdfmark
        [ {Catalog} << /OutputIntents [ {OutputIntent_PDFX} ] >> /PUT pdfmark
        POSTSCRIPT;
    }

    /**
     * Escape a value as a PostScript literal string: backslash first, then the
     * delimiters, so a path or label with parentheses cannot break the syntax.
     */
    private function postScriptString(string $value): string
    {
        return '('.str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value).')';
    }
}
